services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: shopeaseapp-sqlserver
    environment:
      MSSQL_SA_PASSWORD: "itla1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P itla1234! -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.8-alpine
    container_name: shopeaseapp-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
